name = "JUDI4Flux"
uuid = "64d089a9-642e-40bf-b992-0fb13636391a"
authors = ["Ziyi (Francis) Yin<ziyi.yin@gatech.edu>", "Henryk Modzelewski <henryk_modzelewski@mac.com>"]
version = "0.2.1"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
JOLI = "bb331ad6-a1cf-11e9-23da-9bcb53c69f6f"
JUDI = "f3b833dc-6b2e-5b9c-b940-873ed6319979"
SegyIO = "157a0f19-4d44-4de5-a0d0-07e2f0ac4dfa"

[compat]
JOLI = "0.7"
JUDI = "2.5,2.6"
SegyIO = "0.7"
julia = "1"
