name: Tests

on: 
  # Trigger the workflow on push to master or pull request
  # to be merged in master
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      DEVITO_ARCH: gcc
      DEVITO_LANGUAGE: "openmp"
      DEVITO_LOGGING: "ERROR"
      OMP_NUM_THREADS: ${{ matrix.omp }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest]
        version: ['1.6', '1.7']
  
        include:
          - os: macos-latest
            version: '1.6'

    steps:
      - name: Checkout JUDI4Flux
        uses: actions/checkout@v2

      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: x64

      - name: Build JUDI4Flux
        uses: julia-actions/julia-buildpkg@latest

      - name: Run tests
        uses: julia-actions/julia-runtest@latest

      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
